"""Build a local web asset directory for future Android packaging (not an APK)."""
from pathlib import Path
import hashlib
import json
import shutil
import tempfile
import subprocess
from build_map_data import build as build_map

ROOT = Path(__file__).resolve().parents[1]
FOLDERS = ("css", "js", "data", "img", "images", "favicons", "audio", "fonts", "vendor")
FILES = ("index.html", "manifest.json")

def build(root=ROOT):
    root = Path(root).resolve()
    build_map(root)
    dist = root / "dist"
    if dist.is_symlink(): raise ValueError("dist must be a local directory.")
    dist.mkdir(exist_ok=True)
    destination = dist / "android-web"
    if destination.is_symlink() or not destination.resolve().is_relative_to(dist):
        raise ValueError("Invalid output path.")
    if destination.exists() and not (destination/".wiki-web-build").is_file():
        raise ValueError("Output is not a generated Wiki build; nothing was replaced.")
    for number in range(1,387):
        if not (root/f"audio/cries/{number}.ogg").read_bytes().startswith(b"OggS"):
            raise ValueError(f"Invalid or missing cry: {number}")
    with tempfile.TemporaryDirectory(prefix=".android-web-",dir=dist) as temporary:
        stage = Path(temporary)
        for folder in FOLDERS:
            for source in (root/folder).rglob("*"):
                if source.is_symlink() or not source.resolve().is_relative_to(root):
                    raise ValueError("Assets must stay inside the project.")
                if source.is_file():
                    target = stage/source.relative_to(root)
                    target.parent.mkdir(parents=True,exist_ok=True)
                    shutil.copy2(source,target)
        for file in FILES: shutil.copy2(root/file,stage/file)
        bundle_script=("require('esbuild').buildSync({entryPoints:[process.argv[1]],bundle:true,"
                       "format:'iife',target:'chrome89',outfile:process.argv[2]})")
        subprocess.run(["node", "--input-type=commonjs", "-e", bundle_script,
                        str(root/"native/main.js"), str(stage/"native.js")],
                       cwd=root, stdin=subprocess.DEVNULL, check=True)
        # Native packages ship a complete snapshot; a web SW must not replace it.
        index = stage/"index.html"
        text = index.read_text(encoding="utf-8")
        text = text.replace("if ('serviceWorker' in navigator)", "if (false /* native asset snapshot */)")
        text = text.replace("</head>", '<link rel="stylesheet" href="./css/native.css"><script defer src="./native.js"></script></head>')
        index.write_text(text,encoding="utf-8")
        (stage/".wiki-web-build").write_text("Generated by tools/build_android_web.py\n",encoding="utf-8")
        manifest = [{"path":p.relative_to(stage).as_posix(),"bytes":p.stat().st_size,
                     "sha256":hashlib.sha256(p.read_bytes()).hexdigest()}
                    for p in sorted(stage.rglob("*")) if p.is_file() and not p.name.startswith(".")]
        if destination.exists():
            # Only the fixed generated directory above is ever replaced.
            shutil.rmtree(destination)
        stage.rename(destination)
    report={"directory":str(destination),"files":len(manifest),"bytes":sum(p["bytes"] for p in manifest),"assets":manifest}
    (dist/"android-web-manifest.json").write_text(json.dumps(report,indent=2)+"\n",encoding="utf-8")
    return report

if __name__ == "__main__":
    report=build()
    print(json.dumps({k:v for k,v in report.items() if k!="assets"},indent=2))
